# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cp_run <- function(my_time_series_raw, my_time_series_len, my_time_series_d, my_min_segment_size, my_pt, my_is_Euclidean_distance, my_dist_raw, my_block_size, my_change_point_set_raw, my_change_point_num_raw, method) {
    .Call(`_CP_cp_run`, my_time_series_raw, my_time_series_len, my_time_series_d, my_min_segment_size, my_pt, my_is_Euclidean_distance, my_dist_raw, my_block_size, my_change_point_set_raw, my_change_point_num_raw, method)
}

